version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...

builds:
  - id: main-app # Changed ID to 'main-app' to avoid conflict with binary name
    binary: assimilator
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      #- riscv64 # For future expansion
    ldflags:
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
  - id: launcher
    binary: assimilator-launcher
    dir: ./launcher
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      #- riscv64 # For future expansion

nfpms:
  - id: packages
    builds:
      - main-app # Reference the new ID
      - launcher
    formats:
      - deb
      - rpm
      - archlinux
    description: "Facilitates assimilating a machine into the collective."
    license: GNU General Public License v3.0
    maintainer: "geogian28 <geo.sbrohaugh@gmail.com>"
    contents:
      # Source (src) uses the build ID 'launcher'
      - src: launcher
        # Destination (dst) is the desired location in /opt
        dst: /opt/assimilator/bin/assimilator-launcher
        file_info:
          mode: 0755
      # Source (src) uses the new build ID 'main-app'
      - src: main-app
        # Destination (dst) is the desired location in /usr/bin
        dst: /usr/bin/assimilator
        file_info:
          mode: 0755
      - src: ./service/assimilator.service
        dst: /lib/systemd/system/assimilator.service
      - src: ./LICENSE
        dst: /usr/share/doc/assimilator/LICENSE
      - src: ./README.md
        dst: /usr/share/doc/assimilator/README.MD

dockers:
  - id: assimilator
    image_templates:
      - "geogian/assimilator:latest"
      - "geogian/assimilator:{{ .Version }}"
      - "geogian/assimilator:{{ .Major }}"
    dockerfile: DOCKERFILE

archives:
  - formats: [tar.gz]
    builds:
      - main-app # Reference the new ID
      - launcher
    files:
      - LICENSE
      - README.md
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{ .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
