# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...

builds:
  - id: assimilator
    binary: assimilator
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      #- riscv64 # For future expansion
    ldflags:
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
  - id: launcher
    # CHANGE: Use the final desired name for the built binary
    binary: assimilator-launcher
    dir: ./launcher
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      #- riscv64 # For future expansion

nfpms:
  - id: packages
    builds:
      - assimilator
      - launcher
    formats:
      - deb
      - rpm
      - archlinux
    description: "Facilitates assimilating a machine into the collective."
    license: GNU General Public License v3.0
    maintainer: "geogian28 <geo.sbrohaugh@gmail.com>"
    contents:
      # CHANGE: Update src to match the new binary name
      - src: assimilator-launcher
        dst: /opt/assimilator/bin/assimilator-launcher
        file_info:
          mode: 0755
      # assimilator remains correct
      - src: assimilator
        dst: /usr/bin/assimilator
        file_info:
          mode: 0755
      - src: ./service/assimilator.service
        dst: /lib/systemd/system/assimilator.service
      - src: ./LICENSE
        dst: /usr/share/doc/assimilator/LICENSE
      - src: ./README.md
        dst: /usr/share/doc/assimilator/README.MD

dockers:
  - id: assimilator
    image_templates:
      - "geogian/assimilator:latest"
      - "geogian/assimilator:{{ .Version }}"
      - "geogian/assimilator:{{ .Major }}"
    dockerfile: DOCKERFILE

archives:
  - formats: [tar.gz]
    builds:
      - assimilator
      - launcher
    files:
      - LICENSE
      - README.md
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{ .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
