FROM debian:12-slim
RUN apt-get update && apt-get install -y \
    ca-certificates \
    tar \
    gzip \
    && rm -rf /var/lib/apt/lists/*
COPY assimilator /assimilator
# # Set the command to run the binary in agent mode
ENTRYPOINT ["/assimilator"]