---
- name: DotFiles Config
  hosts: localhost
  connection: local
  become: true
  #gather_facts: true

  vars:
    folder:
      - "ISOs"
      - "Zeppelin"
      - "ContainerData"
      - "Homelab"
      - "ContainerData/Cider"
      - "GitRepos"

  tasks:
    #- name: Facts
    #  setup:
    #- name: Dump
    #  run_once: true
    #  copy:
    #    content: "{{ hostvars[inventory_hostname] | to_nice_json }}"
    #    dest: /tmp/setup-dump.json

    - name: update apt packages
      apt:
        update_cache: yes
        upgrade: yes
      when: ansible_facts["os_family"] == "Debian"

    - name: Install nfs-utils for Redhat-like
      package:
        name:
          - nfs-utils
        state: present
      when: ansible_facts["os_family"] == "RedHat"

    - name: Install nfs-common for Debian-like
      package:
        name:
          - nfs-common
        state: present
      when: ansible_facts["os_family"] == "Debian"

    - name: Make mount folder in /mnt/nfs
      ansible.builtin.file:
        path: "{{ '/mnt/nfs/' + item }}"
        state: directory
      with_items: "{{ folder }}"

    - name: Add NFS Shares
      mount:
        src: "{{ 'raihako.brohome.net:/mnt/Raihako/' + item }}"
        path: "{{ '/mnt/nfs/' + item }}"
        opts: rw
        state: mounted
        fstype: nfs
      with_items: "{{ folder }}"

    - name: Get list of user home directories
      ansible.builtin.shell:
        cmd: "ls -d /home/*"
      register: home_dirs

    - name: "Get list of dotfiles roles"
      ansible.builtin.find:
        paths: "/tmp/.assimilator/dotfiles/roles"
        file_type: "directory"
        recurse: false
      register: role_dirs

    - name: "Set dotfiles role list"
      set_fact:
        role_list: "{{ role_dirs.files | map(attribute='path') | map('basename') | list }}"

    - name: "Apply dotfiles roles"
      include_role:
        name: "{{ item }}"
      loop: "{{ role_list }}"

    - name: "Get list of machine_setup roles"
      ansible.builtin.find:
        paths: "/tmp/.assimilator/machine_setup/roles"
        file_type: "directory"
        recurse: false
      register: role_dirs

    - name: "Set machine_setup role list"
      set_fact:
        role_list: "{{ role_dirs.files | map(attribute='path') | map('basename') | list }}"

    - name: "Apply machine_setup roles"
      include_role:
        name: "{{ item }}"
      loop: "{{ role_list }}"