---
- name: Configure Assimilator
  hosts: localhost
  connection: local
  become: true

  vars:
    folder:
      - "ISOs"
      - "Zeppelin"
      - "ContainerData"
      - "Homelab"
      - "ContainerData/Cider"
      - "GitRepos"
    apps:
      - "nano"
      - "micro"
      - "btop"
      - "fzf"
      - "qemu-guest-agent"
      - "zsh"

  tasks:
    - name: update apt packages
      apt:
        update_cache: yes
        upgrade: yes
      when: ansible_facts["os_family"] == "Debian"

    - name: Install nfs-utils for Redhat-like
      package:
        name:
          - nfs-utils
        state: present
      when: ansible_facts["os_family"] == "RedHat"

    - name: Install nfs-common for Debian-like
      package:
        name:
          - nfs-common
        state: present
      when: ansible_facts["os_family"] == "Debian"

    - name: Make mount folder in /mnt/nfs
      ansible.builtin.file:
        path: "{{ '/mnt/nfs/' + item }}"
        state: directory
      with_items: "{{ folder }}"

    - name: Add NFS Shares
      mount:
        src: "{{ 'raihako.brohome.net:/mnt/Raihako/' + item }}"
        path: "{{ '/mnt/nfs/' + item }}"
        opts: rw
        state: mounted
        fstype: nfs
      with_items: "{{ folder }}"

    - name: Get list of user home directories
      ansible.builtin.shell:
        cmd: "ls -d /home/*"
      register: home_dirs
    
    - name: "Get list of machine_setup roles"
      ansible.builtin.find:
        paths: "/etc/assimilator/machine_setup/roles"
        file_type: "directory"
        recurse: false
      register: machine_role_dirs

    - name: "Set machine_setup role list"
      set_fact:
        machine_role_list: "{{ machine_role_dirs.files | map(attribute='path') | list }}"

    - name: "Apply machine_setup roles"
      include_role:
        name: "{{ item }}"
      loop: "{{ machine_role_list }}"

    - name: "Get list of user_setup roles"
      ansible.builtin.find:
        paths: "/etc/assimilator/user_setup/roles"
        file_type: "directory"
        recurse: false
      register: user_role_dirs

    - name: "Set user_setup role list"
      set_fact:
        user_role_list: "{{ user_role_dirs.files | map(attribute='path') | list }}"

    - name: "Apply user_setup roles"
      include_role:
        name: "{{ item }}"
      loop: "{{ user_role_list }}"
