---
- name: "| Copy .zshrc"
  ansible.builtin.copy:
    src: "/tmp/.assimilator/roles/zsh/.zshrc"
    dest: "{{ user_home }}/.zshrc"
    owner: "{{ user_home | basename }}" # Set owner to username
    group: "{{ user_home | basename }}" # Set group to username
    mode: "0644"
    force: true
  loop: "{{ home_dirs.stdout_lines }}"
  loop_control:
    loop_var: user_home
  when: user_home != "/home" # Exclude /home directory itself