version = 2
final_space = true
console_title_template = '{{ .UserName }} in {{ .Folder }} at {{ .HostName }}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newLine = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    template = '<b>╭─</b>'
    background = 'transparent'
    foreground = 'p:gray'

  [[blocks.segments]]
    type = 'path'
    style = 'diamond'
    powerline_symbol = ''
    template = '<b>  {{ path .Path .Location }} </b>'
    foreground = 'p:folder_foreground'
    background = 'p:folder_background'
    leading_diamond = '<transparent,background></>'
    trailing_diamond = ''

    [blocks.segments.properties]
      style = 'agnoster_short'
      max_depth = 2

  [[blocks.segments]]
    type = 'root'
    style = 'powerline'
    powerline_symbol = ''
    template = '  '
    background = 'p:yellow'
    foreground = 'p:white'

[[blocks]]
  type = 'prompt'
  alignment = 'right'
  filler = '─'
  filler_background = 'p:blue'

  [[blocks.segments]]
    type = 'session'
    style = 'diamond'
    leading_diamond = ''
    trailing_diamond = ''
    template = '<b>{{ .UserName }}</b> '
    foreground_templates = ['{{ if eq .UserName "sam" }}p:sam_foreground{{ else }}p:username_foreground{{ end }}']
    background_templates = ['{{ if eq .UserName "sam" }}p:sam_background{{ else }}p:username_background{{ end }}']

  [[blocks.segments]]
    type = 'session'
    style = 'powerline'
    powerline_symbol = ''
    template = '<b>{{ if .SSHSession }}<b>  </b>{{ end }} {{ .HostName }} '
    foreground = 'p:hostname_foreground'
    background = 'p:hostname_background'

  [[blocks.segments]]
    type = "os"
    style = "powerline"
    powerline_symbol = "\uE0CC"
    foreground = "p:os_foreground"
    background = "p:os_background"
    template = " <b>{{.Icon}}</b>"

    [blocks.segments.properties]
      display_distro_name = true

  [[blocks.segments]]
    type = "os"
    style = "powerline"
    powerline_symbol = ''
    foreground = "p:os_foreground"
    background = "p:os_background"
    template = "<b>{{.Icon}} </b>"

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    template = '─╮'
    background = 'transparent'
    foreground = 'p:gray'

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    powerline_symbol = ''
    template = '<b>╰─</b>'
    background = 'transparent'
    foreground = 'p:gray'

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    powerline_symbol = ''
    template = '<b>></b>'
    foreground = 'p:prompt_foreground'
    background = 'p:prompt_background'

[[blocks]]
  type = 'rprompt'
  alignment = 'right'
  filler = '─'
  filler_background = 'p:blue'

  [[blocks.segments]]
    type = "executiontime"
    style = 'plain'
    foreground = 'p:executiontime_foreground'
    background = 'p:executiontime_background'
    template = "<b>{{ .FormattedMs }}</b>"
    
    [blocks.segments.properties]
      threshold = 500
      style = "austin"
      always_enabled = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    template = ' ─╯'
    background = 'transparent'
    foreground = 'p:gray'

blocks = [ ]

[[tooltips]]
  type = "kubectl"
  tips = [ "kubectl", "k", "kn" ]
  style = "diamond"
  leading_diamond = ""
  trailing_diamond = ""
  foreground = "#FFFFFF"
  background = "#326CE5"
  template = "<b> \u2388 {{.Context}}/{{.Namespace}}</b> "

[[tooltips]]
  type = "kubectl"
  tips = [ "kubectl", "k", "kn" ]
  style = "plain"
  foreground = "p:gray"
  background = "background"
  template = "─╯"

[transient_prompt]
  template = '<p:purple,transparent></><p:white,p:purple>{{ .UserName}}@{{ .HostName }}</><p:purple,p:folder_background></><p:folder_foreground,p:folder_background> {{ .Folder }} </><p:folder_background,background></>'
  background = 'transparent'
  foreground = 'p:white'

[secondary_prompt]
  template = '<p:yellow,transparent></><,p:yellow> > </><p:yellow,transparent></> '
  background = 'transparent'
  foreground = 'p:black'


[palette]
  #username_foreground = 'p:white'
  #username_background = 'p:purple'
  #hostname_foreground = 'p:white'
  #hostname_background = 'p:blue'
  #folder_foreground = 'p:white'
  #folder_background = 'p:pink'
  #prompt_foreground = 'p:yellow'
  #prompt_background = 'background'
  #executiontime_foreground = ''
  #executiontime_foreground = ''

  #username_foreground = 'p:macchiato_text'
  #username_background = 'p:macchiato_lavender'
  #hostname_foreground = 'p:macchiato_text'
  #hostname_background = 'p:macchiato_blue'
  #folder_foreground = 'p:macchiato_text'
  #folder_background = 'p:macchiato_pink'
  #prompt_foreground = 'p:macchiato_os'
  #prompt_background = 'background'
  #executiontime_foreground = ''
  #executiontime_foreground = ''

  username_foreground = 'p:dark_blue'
  username_background = 'p:cyberpunk_2'
  sam_foreground = 'p:black'
  sam_background = 'p:green'
  hostname_foreground = 'p:blue'
  hostname_background = 'p:co_4'
  folder_foreground = 'p:cyberpunk_3'
  folder_background = 'p:cyberpunk_5'
  prompt_foreground = 'p:cyberpunk_3'
  prompt_background = 'background'
  executiontime_foreground = 'p:blue'
  executiontime_background = 'background'
  os_foreground = 'p:co_4'
  os_background = 'p:blue'

  black = '#262B44'
  green = '#39b355'
  orange = '#F07623'
  red = '#D81E5B'
  white = '#FFFFFF'
  gray = '#999999'
  yellow = '#F3AE35'
  blue = '#4B95E9'
  dark_blue = '#2664ab'
  purple = '#791e94'
  dark_purple = '#241734'
  pink = '#D40078'
  dark_pink = '#fc65bb'

  macchiato_os = "#ACB0BE"
  macchiato_pink = "#F5BDE6"
  macchiato_lavender = "#B7BDF8"
  macchiato_blue =  "#8AADF4"
  macchiato_white = "#FFFFFF"
  macchiato_text = "#494D64"

  cyberpunk_1 = '#b0acb0'
  cyberpunk_2 = '#e2dddf'
  cyberpunk_3 = '#85ebd9'
  cyberpunk_4 = '#3d898d'
  cyberpunk_5 = '#2f404d'

  co_1 = '#0c8054'
  co_2 = '#006a4f'
  co_3 = '#004241'
  co_4 = '#333333'
  co_5 = '#010b13'
  co_6 = '#ea6400'

#[palette]
#  os = "#ACB0BE"
#  pink = "#F5BDE6"
#  lavender = "#B7BDF8"
#  blue =  "#8AADF4"
#  white = "#FFFFFF"
#  text = "#494D64"

#[palette]
#  black = '#262B44'
#  blue = '#4B95E9'
#  green = '#39b355'
#  dark_green = '#00801a'
#  orange = '#F07623'
#  red = '#D81E5B'
#  white = '#E0DEF4'
#  yellow = '#F3AE35'
