---
- name: Install apps for all distros
  package:
    name:
      - "{{ app }}"
    state: present
  with_items: "{{ apps }}"
  loop_control:
    loop_var: app

- block:
  - name: Check if oh-my-posh is installed
    command: "which /usr/local/bin/oh-my-posh"
  rescue:
    - name: Install oh-my-posh via curl script
      shell: "curl -s https://ohmyposh.dev/install.sh | bash -s -- -d /usr/local/bin/"