---
- name: Install apps for all distros
  package:
    name:
      - "{{ app }}"
    state: present
  with_items: "{{ apps }}"
  loop_control:
    loop_var: app

- name: Install oh-my-posh via curl script
  command: "! [ -f /usr/local/bin/oh-my-posh ] && curl -s https://ohmyposh.dev/install.sh | bash -s -- -d /usr/local/bin/oh-my-posh"