---
- name: Install apps for all distros
  package:
    name:
      - "{{ app }}"
    state: present
  with_items: "{{ apps }}"
  loop_control:
    loop_var: app

- name: Check if oh-my-posh is installed
  stat:
    path: "/usr/local/bin/oh-my-posh"
  register: oh_my_posh

- name: Install oh-my-posh via curl script
  shell: "curl -s https://ohmyposh.dev/install.sh | bash -s -- -d /usr/local/bin/"
  when: oh_my_posh.stat.exists is false
    