---
- name: Install nfs-common for Debian-like
  package:
    name:
      - nfs-common
    state: present
  when: ansible_facts["os_family"] == "Debian"

- name: Install nfs-utils for Redhat-like
  package:
    name:
      - nfs-utils
    state: present
  when: ansible_facts["os_family"] == "Fedora"

- name: Install nfs-common for Debian-like
  package:
    name:
      - autofs
    state: present

- name: Uncomment line from /etc/auto.master
  lineinfile:
    path: /etc/auto.master
    line: /nfs    -hosts
    create: yes

- name: Create /mnt/nfs folder
  file:
    path: /mnt/nfs
    state: directory

- name: add NFS Symlinks
  file:
    path: "/mnt/nfs/{{ link }}"
    state: link
    target: /nfs/Raihako/mnt/Raihako/{{ link }}
  loop_control:
    loop_var: link
  with_items:
    - /nfs
# - name: Make mount folder in /mnt/nfs
#   ansible.builtin.file:
#     path: "{{ '/mnt/nfs/' + mount_folder }}"
#     state: directory
#   with_items: "{{ folder }}"
#   loop_control:
#       loop_var: mount_folder

# - name: Add NFS Shares
#   mount:
#     src: "{{ 'raihako.brohome.net:/mnt/Raihako/' + mount_folder }}"
#     path: "{{ '/mnt/nfs/' + mount_folder }}"
#     opts: rw
#     state: mounted
#     fstype: nfs
#   with_items: "{{ folder }}"
#   loop_control:
#       loop_var: mount_folder
