---
- name: Set DNS to 192.168.0.40
  replace:
    path: /etc/systemd/resolved.conf
    regexp: "^#DNS=.*"
    replace: "DNS=192.168.0.40"

- name: Set Search Domain to brohome.net
  replace:
    path: /etc/systemd/resolved.conf
    regexp: "^#Domains=.*"
    replace: "Domains=brohome.net"

- name: Check if using the default hostname
  shell:
    cmd: hostnamectl | grep -vqz ubuntu
  changed_when: false
  check_mode: false
  register: default_hostname
  no_log: true

- name: Warn about default hostname
  fail:
    msg: "Default hostname detected. Please change before joining domain."
  when: default_hostname.rc == 1

- name: Make sure "realm" command is installed
  package:
    name:
      - realmd
    state: present

- name: Check if system is already domain joined
  shell:
    cmd: realm list
  changed_when: false
  check_mode: false
  register: domain_joined

- name: Install FreeIPA Client
  package:
    name:
      - freeipa-client
    state: present

- name: Join FreeIPA domain
  expect:
    command: /bin/bash -c  "realm join --user={{ admin_user }}  {{ freeipa_domain }}""
    responses:
      "Password for .*: ": "{{ admin_password }}"
    echo: true
    timeout: 300
  register: ipa_join_result
  changed_when: ipa_join_result.rc != 0
  failed_when: ipa_join_result.rc != 0
  when: "'brohome.net' not in domain_joined.stdout"

- name: Ensure sssd service is running and enabled
  systemd:
    name: sssd
    state: started
    enabled: true
