---
- name: "| Copy .bashrc"
  ansible.builtin.copy:
    src: "{{ role_path }}/files/.bashrc"
    dest: "{{ user_home }}/.bashrc"
    owner: "{{ user_home | basename }}" # Set owner to username
    group: "{{ user_home | basename }}" # Set group to username
    mode: "0644"
    force: true
  loop: "{{ home_dirs.stdout_lines }}"
  loop_control:
    loop_var: user_home
  when: user_home != "/home" # Exclude /home directory itself