// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: assctl.proto

package assctl

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAllConfigsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllConfigsRequest) Reset() {
	*x = GetAllConfigsRequest{}
	mi := &file_assctl_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllConfigsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllConfigsRequest) ProtoMessage() {}

func (x *GetAllConfigsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assctl_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllConfigsRequest.ProtoReflect.Descriptor instead.
func (*GetAllConfigsRequest) Descriptor() ([]byte, []int) {
	return file_assctl_proto_rawDescGZIP(), []int{0}
}

type GetAllConfigsResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Machines      map[string]*MachineConfig `protobuf:"bytes,1,rep,name=Machines,proto3" json:"Machines,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Users         map[string]*UserConfig    `protobuf:"bytes,2,rep,name=Users,proto3" json:"Users,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllConfigsResponse) Reset() {
	*x = GetAllConfigsResponse{}
	mi := &file_assctl_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllConfigsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllConfigsResponse) ProtoMessage() {}

func (x *GetAllConfigsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assctl_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllConfigsResponse.ProtoReflect.Descriptor instead.
func (*GetAllConfigsResponse) Descriptor() ([]byte, []int) {
	return file_assctl_proto_rawDescGZIP(), []int{1}
}

func (x *GetAllConfigsResponse) GetMachines() map[string]*MachineConfig {
	if x != nil {
		return x.Machines
	}
	return nil
}

func (x *GetAllConfigsResponse) GetUsers() map[string]*UserConfig {
	if x != nil {
		return x.Users
	}
	return nil
}

type GetSpecificConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MachineName   string                 `protobuf:"bytes,1,opt,name=MachineName,proto3" json:"MachineName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSpecificConfigRequest) Reset() {
	*x = GetSpecificConfigRequest{}
	mi := &file_assctl_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSpecificConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSpecificConfigRequest) ProtoMessage() {}

func (x *GetSpecificConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assctl_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSpecificConfigRequest.ProtoReflect.Descriptor instead.
func (*GetSpecificConfigRequest) Descriptor() ([]byte, []int) {
	return file_assctl_proto_rawDescGZIP(), []int{2}
}

func (x *GetSpecificConfigRequest) GetMachineName() string {
	if x != nil {
		return x.MachineName
	}
	return ""
}

type GetSpecificConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       *ServerVersion         `protobuf:"bytes,1,opt,name=Version,proto3" json:"Version,omitempty"`
	Machine       *MachineConfig         `protobuf:"bytes,2,opt,name=Machine,proto3" json:"Machine,omitempty"`
	Users         map[string]*UserConfig `protobuf:"bytes,3,rep,name=Users,proto3" json:"Users,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSpecificConfigResponse) Reset() {
	*x = GetSpecificConfigResponse{}
	mi := &file_assctl_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSpecificConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSpecificConfigResponse) ProtoMessage() {}

func (x *GetSpecificConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assctl_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSpecificConfigResponse.ProtoReflect.Descriptor instead.
func (*GetSpecificConfigResponse) Descriptor() ([]byte, []int) {
	return file_assctl_proto_rawDescGZIP(), []int{3}
}

func (x *GetSpecificConfigResponse) GetVersion() *ServerVersion {
	if x != nil {
		return x.Version
	}
	return nil
}

func (x *GetSpecificConfigResponse) GetMachine() *MachineConfig {
	if x != nil {
		return x.Machine
	}
	return nil
}

func (x *GetSpecificConfigResponse) GetUsers() map[string]*UserConfig {
	if x != nil {
		return x.Users
	}
	return nil
}

type ServerVersion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Commit        string                 `protobuf:"bytes,2,opt,name=commit,proto3" json:"commit,omitempty"`
	BuildDate     string                 `protobuf:"bytes,3,opt,name=build_date,json=buildDate,proto3" json:"build_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerVersion) Reset() {
	*x = ServerVersion{}
	mi := &file_assctl_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerVersion) ProtoMessage() {}

func (x *ServerVersion) ProtoReflect() protoreflect.Message {
	mi := &file_assctl_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerVersion.ProtoReflect.Descriptor instead.
func (*ServerVersion) Descriptor() ([]byte, []int) {
	return file_assctl_proto_rawDescGZIP(), []int{4}
}

func (x *ServerVersion) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ServerVersion) GetCommit() string {
	if x != nil {
		return x.Commit
	}
	return ""
}

func (x *ServerVersion) GetBuildDate() string {
	if x != nil {
		return x.BuildDate
	}
	return ""
}

type DesiredState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// AppConfig     global    =1;
	Profiles      map[string]*ConfigProfile `protobuf:"bytes,2,rep,name=profiles,proto3" json:"profiles,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Machines      map[string]*MachineConfig `protobuf:"bytes,3,rep,name=machines,proto3" json:"machines,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Users         map[string]*UserConfig    `protobuf:"bytes,4,rep,name=users,proto3" json:"users,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DesiredState) Reset() {
	*x = DesiredState{}
	mi := &file_assctl_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DesiredState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DesiredState) ProtoMessage() {}

func (x *DesiredState) ProtoReflect() protoreflect.Message {
	mi := &file_assctl_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DesiredState.ProtoReflect.Descriptor instead.
func (*DesiredState) Descriptor() ([]byte, []int) {
	return file_assctl_proto_rawDescGZIP(), []int{5}
}

func (x *DesiredState) GetProfiles() map[string]*ConfigProfile {
	if x != nil {
		return x.Profiles
	}
	return nil
}

func (x *DesiredState) GetMachines() map[string]*MachineConfig {
	if x != nil {
		return x.Machines
	}
	return nil
}

func (x *DesiredState) GetUsers() map[string]*UserConfig {
	if x != nil {
		return x.Users
	}
	return nil
}

type ConfigProfile struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Machines      map[string]*MachineConfig `protobuf:"bytes,1,rep,name=machines,proto3" json:"machines,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Users         map[string]*UserConfig    `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigProfile) Reset() {
	*x = ConfigProfile{}
	mi := &file_assctl_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigProfile) ProtoMessage() {}

func (x *ConfigProfile) ProtoReflect() protoreflect.Message {
	mi := &file_assctl_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigProfile.ProtoReflect.Descriptor instead.
func (*ConfigProfile) Descriptor() ([]byte, []int) {
	return file_assctl_proto_rawDescGZIP(), []int{6}
}

func (x *ConfigProfile) GetMachines() map[string]*MachineConfig {
	if x != nil {
		return x.Machines
	}
	return nil
}

func (x *ConfigProfile) GetUsers() map[string]*UserConfig {
	if x != nil {
		return x.Users
	}
	return nil
}

type MachineConfig struct {
	state           protoimpl.MessageState    `protogen:"open.v1"`
	AppliedProfiles []string                  `protobuf:"bytes,1,rep,name=appliedProfiles,proto3" json:"appliedProfiles,omitempty"`
	Packages        map[string]*PackageConfig `protobuf:"bytes,2,rep,name=packages,proto3" json:"packages,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // map<string, ServiceConfig> services = 3;
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MachineConfig) Reset() {
	*x = MachineConfig{}
	mi := &file_assctl_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineConfig) ProtoMessage() {}

func (x *MachineConfig) ProtoReflect() protoreflect.Message {
	mi := &file_assctl_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineConfig.ProtoReflect.Descriptor instead.
func (*MachineConfig) Descriptor() ([]byte, []int) {
	return file_assctl_proto_rawDescGZIP(), []int{7}
}

func (x *MachineConfig) GetAppliedProfiles() []string {
	if x != nil {
		return x.AppliedProfiles
	}
	return nil
}

func (x *MachineConfig) GetPackages() map[string]*PackageConfig {
	if x != nil {
		return x.Packages
	}
	return nil
}

type UserConfig struct {
	state           protoimpl.MessageState    `protogen:"open.v1"`
	AppliedProfiles []string                  `protobuf:"bytes,1,rep,name=appliedProfiles,proto3" json:"appliedProfiles,omitempty"`
	Packages        map[string]*PackageConfig `protobuf:"bytes,2,rep,name=packages,proto3" json:"packages,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UserConfig) Reset() {
	*x = UserConfig{}
	mi := &file_assctl_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserConfig) ProtoMessage() {}

func (x *UserConfig) ProtoReflect() protoreflect.Message {
	mi := &file_assctl_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserConfig.ProtoReflect.Descriptor instead.
func (*UserConfig) Descriptor() ([]byte, []int) {
	return file_assctl_proto_rawDescGZIP(), []int{8}
}

func (x *UserConfig) GetAppliedProfiles() []string {
	if x != nil {
		return x.AppliedProfiles
	}
	return nil
}

func (x *UserConfig) GetPackages() map[string]*PackageConfig {
	if x != nil {
		return x.Packages
	}
	return nil
}

type PackageConfig struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	State   string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Version string                 `protobuf:"bytes,2,opt,name=version,json=version,omitempty,proto3" json:"version,omitempty"`
	Branch  string                 `protobuf:"bytes,3,opt,name=branch,json=branch,omitempty,proto3" json:"branch,omitempty"`
	// map<string, Dependencies> requires = 4 [json_name = "requires,omitempty"];
	Checksum      string `protobuf:"bytes,5,opt,name=checksum,proto3" json:"checksum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PackageConfig) Reset() {
	*x = PackageConfig{}
	mi := &file_assctl_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackageConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageConfig) ProtoMessage() {}

func (x *PackageConfig) ProtoReflect() protoreflect.Message {
	mi := &file_assctl_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageConfig.ProtoReflect.Descriptor instead.
func (*PackageConfig) Descriptor() ([]byte, []int) {
	return file_assctl_proto_rawDescGZIP(), []int{9}
}

func (x *PackageConfig) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *PackageConfig) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PackageConfig) GetBranch() string {
	if x != nil {
		return x.Branch
	}
	return ""
}

func (x *PackageConfig) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

type PackageRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PackageName     string                 `protobuf:"bytes,1,opt,name=PackageName,proto3" json:"PackageName,omitempty"`
	PackageChecksum string                 `protobuf:"bytes,2,opt,name=PackageChecksum,proto3" json:"PackageChecksum,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PackageRequest) Reset() {
	*x = PackageRequest{}
	mi := &file_assctl_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageRequest) ProtoMessage() {}

func (x *PackageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_assctl_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageRequest.ProtoReflect.Descriptor instead.
func (*PackageRequest) Descriptor() ([]byte, []int) {
	return file_assctl_proto_rawDescGZIP(), []int{10}
}

func (x *PackageRequest) GetPackageName() string {
	if x != nil {
		return x.PackageName
	}
	return ""
}

func (x *PackageRequest) GetPackageChecksum() string {
	if x != nil {
		return x.PackageChecksum
	}
	return ""
}

type PackageResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The actual binary data.
	// Standard chunk size is usually 32KB or 64KB.
	Content []byte `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	// Optional: The total size of the file in bytes.
	// The server usually only populates this in the VERY FIRST chunk
	// so the client can initialize a progress bar. It sends 0 for the rest.
	TotalSize     int64 `protobuf:"varint,2,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PackageResponse) Reset() {
	*x = PackageResponse{}
	mi := &file_assctl_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageResponse) ProtoMessage() {}

func (x *PackageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_assctl_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageResponse.ProtoReflect.Descriptor instead.
func (*PackageResponse) Descriptor() ([]byte, []int) {
	return file_assctl_proto_rawDescGZIP(), []int{11}
}

func (x *PackageResponse) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *PackageResponse) GetTotalSize() int64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

var File_assctl_proto protoreflect.FileDescriptor

const file_assctl_proto_rawDesc = "" +
	"\n" +
	"\fassctl.proto\x12\x06assctl\"\x16\n" +
	"\x14GetAllConfigsRequest\"\xc2\x02\n" +
	"\x15GetAllConfigsResponse\x12G\n" +
	"\bMachines\x18\x01 \x03(\v2+.assctl.GetAllConfigsResponse.MachinesEntryR\bMachines\x12>\n" +
	"\x05Users\x18\x02 \x03(\v2(.assctl.GetAllConfigsResponse.UsersEntryR\x05Users\x1aR\n" +
	"\rMachinesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.assctl.MachineConfigR\x05value:\x028\x01\x1aL\n" +
	"\n" +
	"UsersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.assctl.UserConfigR\x05value:\x028\x01\"<\n" +
	"\x18GetSpecificConfigRequest\x12 \n" +
	"\vMachineName\x18\x01 \x01(\tR\vMachineName\"\x8f\x02\n" +
	"\x19GetSpecificConfigResponse\x12/\n" +
	"\aVersion\x18\x01 \x01(\v2\x15.assctl.ServerVersionR\aVersion\x12/\n" +
	"\aMachine\x18\x02 \x01(\v2\x15.assctl.MachineConfigR\aMachine\x12B\n" +
	"\x05Users\x18\x03 \x03(\v2,.assctl.GetSpecificConfigResponse.UsersEntryR\x05Users\x1aL\n" +
	"\n" +
	"UsersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.assctl.UserConfigR\x05value:\x028\x01\"`\n" +
	"\rServerVersion\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x16\n" +
	"\x06commit\x18\x02 \x01(\tR\x06commit\x12\x1d\n" +
	"\n" +
	"build_date\x18\x03 \x01(\tR\tbuildDate\"\xbb\x03\n" +
	"\fDesiredState\x12>\n" +
	"\bprofiles\x18\x02 \x03(\v2\".assctl.DesiredState.ProfilesEntryR\bprofiles\x12>\n" +
	"\bmachines\x18\x03 \x03(\v2\".assctl.DesiredState.MachinesEntryR\bmachines\x125\n" +
	"\x05users\x18\x04 \x03(\v2\x1f.assctl.DesiredState.UsersEntryR\x05users\x1aR\n" +
	"\rProfilesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.assctl.ConfigProfileR\x05value:\x028\x01\x1aR\n" +
	"\rMachinesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.assctl.MachineConfigR\x05value:\x028\x01\x1aL\n" +
	"\n" +
	"UsersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.assctl.UserConfigR\x05value:\x028\x01\"\xaa\x02\n" +
	"\rConfigProfile\x12?\n" +
	"\bmachines\x18\x01 \x03(\v2#.assctl.ConfigProfile.MachinesEntryR\bmachines\x126\n" +
	"\x05users\x18\x02 \x03(\v2 .assctl.ConfigProfile.UsersEntryR\x05users\x1aR\n" +
	"\rMachinesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.assctl.MachineConfigR\x05value:\x028\x01\x1aL\n" +
	"\n" +
	"UsersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.assctl.UserConfigR\x05value:\x028\x01\"\xce\x01\n" +
	"\rMachineConfig\x12(\n" +
	"\x0fappliedProfiles\x18\x01 \x03(\tR\x0fappliedProfiles\x12?\n" +
	"\bpackages\x18\x02 \x03(\v2#.assctl.MachineConfig.PackagesEntryR\bpackages\x1aR\n" +
	"\rPackagesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.assctl.PackageConfigR\x05value:\x028\x01\"\xc8\x01\n" +
	"\n" +
	"UserConfig\x12(\n" +
	"\x0fappliedProfiles\x18\x01 \x03(\tR\x0fappliedProfiles\x12<\n" +
	"\bpackages\x18\x02 \x03(\v2 .assctl.UserConfig.PackagesEntryR\bpackages\x1aR\n" +
	"\rPackagesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.assctl.PackageConfigR\x05value:\x028\x01\"\x87\x01\n" +
	"\rPackageConfig\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\x12\"\n" +
	"\aversion\x18\x02 \x01(\tR\x11version,omitempty\x12 \n" +
	"\x06branch\x18\x03 \x01(\tR\x10branch,omitempty\x12\x1a\n" +
	"\bchecksum\x18\x05 \x01(\tR\bchecksum\"\\\n" +
	"\x0ePackageRequest\x12 \n" +
	"\vPackageName\x18\x01 \x01(\tR\vPackageName\x12(\n" +
	"\x0fPackageChecksum\x18\x02 \x01(\tR\x0fPackageChecksum\"J\n" +
	"\x0fPackageResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\fR\acontent\x12\x1d\n" +
	"\n" +
	"total_size\x18\x02 \x01(\x03R\ttotalSize2\x81\x02\n" +
	"\vAssimilator\x12N\n" +
	"\rGetAllConfigs\x12\x1c.assctl.GetAllConfigsRequest\x1a\x1d.assctl.GetAllConfigsResponse\"\x00\x12Z\n" +
	"\x11GetSpecificConfig\x12 .assctl.GetSpecificConfigRequest\x1a!.assctl.GetSpecificConfigResponse\"\x00\x12F\n" +
	"\x0fDownloadPackage\x12\x16.assctl.PackageRequest\x1a\x17.assctl.PackageResponse\"\x000\x01B\n" +
	"Z\b./assctlb\x06proto3"

var (
	file_assctl_proto_rawDescOnce sync.Once
	file_assctl_proto_rawDescData []byte
)

func file_assctl_proto_rawDescGZIP() []byte {
	file_assctl_proto_rawDescOnce.Do(func() {
		file_assctl_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_assctl_proto_rawDesc), len(file_assctl_proto_rawDesc)))
	})
	return file_assctl_proto_rawDescData
}

var file_assctl_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_assctl_proto_goTypes = []any{
	(*GetAllConfigsRequest)(nil),      // 0: assctl.GetAllConfigsRequest
	(*GetAllConfigsResponse)(nil),     // 1: assctl.GetAllConfigsResponse
	(*GetSpecificConfigRequest)(nil),  // 2: assctl.GetSpecificConfigRequest
	(*GetSpecificConfigResponse)(nil), // 3: assctl.GetSpecificConfigResponse
	(*ServerVersion)(nil),             // 4: assctl.ServerVersion
	(*DesiredState)(nil),              // 5: assctl.DesiredState
	(*ConfigProfile)(nil),             // 6: assctl.ConfigProfile
	(*MachineConfig)(nil),             // 7: assctl.MachineConfig
	(*UserConfig)(nil),                // 8: assctl.UserConfig
	(*PackageConfig)(nil),             // 9: assctl.PackageConfig
	(*PackageRequest)(nil),            // 10: assctl.PackageRequest
	(*PackageResponse)(nil),           // 11: assctl.PackageResponse
	nil,                               // 12: assctl.GetAllConfigsResponse.MachinesEntry
	nil,                               // 13: assctl.GetAllConfigsResponse.UsersEntry
	nil,                               // 14: assctl.GetSpecificConfigResponse.UsersEntry
	nil,                               // 15: assctl.DesiredState.ProfilesEntry
	nil,                               // 16: assctl.DesiredState.MachinesEntry
	nil,                               // 17: assctl.DesiredState.UsersEntry
	nil,                               // 18: assctl.ConfigProfile.MachinesEntry
	nil,                               // 19: assctl.ConfigProfile.UsersEntry
	nil,                               // 20: assctl.MachineConfig.PackagesEntry
	nil,                               // 21: assctl.UserConfig.PackagesEntry
}
var file_assctl_proto_depIdxs = []int32{
	12, // 0: assctl.GetAllConfigsResponse.Machines:type_name -> assctl.GetAllConfigsResponse.MachinesEntry
	13, // 1: assctl.GetAllConfigsResponse.Users:type_name -> assctl.GetAllConfigsResponse.UsersEntry
	4,  // 2: assctl.GetSpecificConfigResponse.Version:type_name -> assctl.ServerVersion
	7,  // 3: assctl.GetSpecificConfigResponse.Machine:type_name -> assctl.MachineConfig
	14, // 4: assctl.GetSpecificConfigResponse.Users:type_name -> assctl.GetSpecificConfigResponse.UsersEntry
	15, // 5: assctl.DesiredState.profiles:type_name -> assctl.DesiredState.ProfilesEntry
	16, // 6: assctl.DesiredState.machines:type_name -> assctl.DesiredState.MachinesEntry
	17, // 7: assctl.DesiredState.users:type_name -> assctl.DesiredState.UsersEntry
	18, // 8: assctl.ConfigProfile.machines:type_name -> assctl.ConfigProfile.MachinesEntry
	19, // 9: assctl.ConfigProfile.users:type_name -> assctl.ConfigProfile.UsersEntry
	20, // 10: assctl.MachineConfig.packages:type_name -> assctl.MachineConfig.PackagesEntry
	21, // 11: assctl.UserConfig.packages:type_name -> assctl.UserConfig.PackagesEntry
	7,  // 12: assctl.GetAllConfigsResponse.MachinesEntry.value:type_name -> assctl.MachineConfig
	8,  // 13: assctl.GetAllConfigsResponse.UsersEntry.value:type_name -> assctl.UserConfig
	8,  // 14: assctl.GetSpecificConfigResponse.UsersEntry.value:type_name -> assctl.UserConfig
	6,  // 15: assctl.DesiredState.ProfilesEntry.value:type_name -> assctl.ConfigProfile
	7,  // 16: assctl.DesiredState.MachinesEntry.value:type_name -> assctl.MachineConfig
	8,  // 17: assctl.DesiredState.UsersEntry.value:type_name -> assctl.UserConfig
	7,  // 18: assctl.ConfigProfile.MachinesEntry.value:type_name -> assctl.MachineConfig
	8,  // 19: assctl.ConfigProfile.UsersEntry.value:type_name -> assctl.UserConfig
	9,  // 20: assctl.MachineConfig.PackagesEntry.value:type_name -> assctl.PackageConfig
	9,  // 21: assctl.UserConfig.PackagesEntry.value:type_name -> assctl.PackageConfig
	0,  // 22: assctl.Assimilator.GetAllConfigs:input_type -> assctl.GetAllConfigsRequest
	2,  // 23: assctl.Assimilator.GetSpecificConfig:input_type -> assctl.GetSpecificConfigRequest
	10, // 24: assctl.Assimilator.DownloadPackage:input_type -> assctl.PackageRequest
	1,  // 25: assctl.Assimilator.GetAllConfigs:output_type -> assctl.GetAllConfigsResponse
	3,  // 26: assctl.Assimilator.GetSpecificConfig:output_type -> assctl.GetSpecificConfigResponse
	11, // 27: assctl.Assimilator.DownloadPackage:output_type -> assctl.PackageResponse
	25, // [25:28] is the sub-list for method output_type
	22, // [22:25] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_assctl_proto_init() }
func file_assctl_proto_init() {
	if File_assctl_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_assctl_proto_rawDesc), len(file_assctl_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_assctl_proto_goTypes,
		DependencyIndexes: file_assctl_proto_depIdxs,
		MessageInfos:      file_assctl_proto_msgTypes,
	}.Build()
	File_assctl_proto = out.File
	file_assctl_proto_goTypes = nil
	file_assctl_proto_depIdxs = nil
}
