---
- name: check if Assimilator is installed
  stat:
    path: /usr/local/bin/assimilator
  register: assimilator

- name: "Create link for Assimilator in /usr/local/bin"
  file:
    src: "{{ ASSIMILATOR_DIR }}/assimilator.sh"
    dest: "/usr/local/bin/assimilator"
    state: hard
    owner: "sam"
    group: "sam"
    mode: "755"
  when: assimilator.stat.exists is false

- name: "Set assimilator.sh permissions"
  file:
    path: "{{ ASSIMILATOR_DIR }}/assimilator.sh"
    mode: "755"