---
- name: "Ensure ~/.config/k9s directory exists"
  ansible.builtin.file:
    path: "{{ user_home }}/.config/k9s"
    state: directory
    owner: "{{ user_home | basename }}" # Set owner to username
    group: "{{ user_home | basename }}" # Set group to username
    mode: "0755"
  loop: "{{ home_dirs.stdout_lines }}"
  loop_control:
    loop_var: user_home
  when: user_home != "/home" # Exclude /home directory itself

- name: "| Copy config.yaml"
  ansible.builtin.copy:
    src: "{{ role_path }}/files/"
    dest: "{{ user_home }}/.config/k9s"
    owner: "{{ user_home | basename }}" # Set owner to username
    group: "{{ user_home | basename }}" # Set group to username
    mode: "0644"
    force: true
  loop: "{{ home_dirs.stdout_lines }}"
  loop_control:
    loop_var: user_home
  when: user_home != "/home" # Exclude /home directory itself